/**
 * human-gate-requests.ts
 *
 * Defines the structured human validation gates for the Content Writer agent.
 *
 * These are capabilities the agent cannot perform autonomously:
 *   - Competitive analysis
 *   - A/B variant generation
 *   - Audience persona buildup
 *   - Style guide enforcement
 *   - Distribution planning
 *   - Legal/compliance review
 *   - Evergreen content maintenance
 *   - AI disclosure metadata
 *
 * When the agent reaches one of these gaps, it calls workspace_cw_request_human_gate.
 * The action routes to the approval queue (always high-risk) so the admin/customer
 * can review the draft context and approve, reject, or provide guidance.
 *
 * Security note: all summary/label strings are derived from FIXED template text —
 * never from raw user-supplied draft body content — to prevent prompt injection
 * in the approval queue.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * The set of human validation gates the Content Writer agent can request.
 *
 * Mandatory blockers (legal/compliance risk):
 *   - legal_review   — must not publish without legal sign-off
 *   - ai_disclosure  — AI-generated content disclosure is legally required in many jurisdictions
 *
 * Advisory gates (strategy/quality gaps):
 *   - competitive_analysis, ab_variant, audience_persona, style_guide,
 *     distribution_plan, evergreen_update
 */
export type ContentWriterGateType =
    | 'competitive_analysis'
    | 'ab_variant'
    | 'audience_persona'
    | 'style_guide'
    | 'distribution_plan'
    | 'legal_review'
    | 'evergreen_update'
    | 'ai_disclosure';

/** Risk levels for each gate type. Used to set riskLevel in the routing decision. */
export const GATE_RISK_LEVELS: Record<ContentWriterGateType, 'medium' | 'high'> = {
    competitive_analysis: 'medium',
    ab_variant: 'medium',
    audience_persona: 'medium',
    style_guide: 'medium',
    distribution_plan: 'medium',
    legal_review: 'high',
    evergreen_update: 'medium',
    ai_disclosure: 'high',
};

/** Human-readable display labels shown in the dashboard approval queue. */
const GATE_LABELS: Record<ContentWriterGateType, string> = {
    competitive_analysis: 'Competitive Analysis',
    ab_variant: 'A/B Variant Generation',
    audience_persona: 'Audience Persona Buildup',
    style_guide: 'Style Guide Enforcement',
    distribution_plan: 'Distribution Planning',
    legal_review: 'Legal / Compliance Review',
    evergreen_update: 'Evergreen Content Update',
    ai_disclosure: 'AI Disclosure Metadata',
};

/**
 * Fixed template questions — what the reviewer is being asked to do.
 * These are NEVER populated with user-supplied content to prevent injection.
 */
const GATE_QUESTIONS: Record<ContentWriterGateType, string> = {
    competitive_analysis:
        'The agent cannot scan competitor content. Please review the landscape and confirm positioning before approving publication.',
    ab_variant:
        'The agent produced one draft. Please confirm this single version is sufficient, or reject to request an A/B variant from the Content Writer.',
    audience_persona:
        'The agent received only an audience label (not a full persona). Please confirm goals, pain points, and tone expectations are met, then approve.',
    style_guide:
        'The agent applied heuristic brand voice matching. Please validate the draft meets your style guide and approve or provide correction notes.',
    distribution_plan:
        'No distribution strategy is configured. Please confirm publish channels, social scheduling, and email targeting before approving.',
    legal_review:
        'This content contains claims that may require legal review. Do NOT approve until your legal team has cleared the draft.',
    evergreen_update:
        'This content is scheduled for an evergreen refresh. Please confirm all factual claims are still accurate before approving re-publication.',
    ai_disclosure:
        'This content was generated by an AI agent. Please confirm required AI-authorship disclosure metadata is present before approving publication.',
};

/** Category tag displayed as a badge in the approval panel. */
export const GATE_CATEGORIES: Record<ContentWriterGateType, 'compliance' | 'strategy' | 'quality'> = {
    competitive_analysis: 'strategy',
    ab_variant: 'strategy',
    audience_persona: 'quality',
    style_guide: 'quality',
    distribution_plan: 'strategy',
    legal_review: 'compliance',
    evergreen_update: 'quality',
    ai_disclosure: 'compliance',
};

// ---------------------------------------------------------------------------
// Input / output types
// ---------------------------------------------------------------------------

/** Structured request the agent builds before calling workspace_cw_request_human_gate. */
export interface HumanGateInput {
    /** One of the defined gate types. */
    gateType: ContentWriterGateType;
    /** Article/post title — truncated and sanitized before display. */
    title: string;
    /** Research topic. */
    topic: string;
    /** Word count of the current draft, if available. */
    wordCount?: number;
    /** CMS target / publish channel, if known. */
    publishTarget?: string;
}

/** The validated, display-safe record returned from buildHumanGateRecord(). */
export interface HumanGateRecord {
    gateType: ContentWriterGateType;
    label: string;
    question: string;
    category: 'compliance' | 'strategy' | 'quality';
    riskLevel: 'medium' | 'high';
    /** Sanitized title — no HTML/special chars, max 80 chars. */
    safeTitle: string;
    /** Sanitized topic — no HTML/special chars, max 80 chars. */
    safeTopic: string;
    wordCount: number | null;
    publishTarget: string | null;
}

// ---------------------------------------------------------------------------
// Guards + builders
// ---------------------------------------------------------------------------

const VALID_GATE_TYPES = new Set<string>([
    'competitive_analysis', 'ab_variant', 'audience_persona',
    'style_guide', 'distribution_plan', 'legal_review',
    'evergreen_update', 'ai_disclosure',
]);

export function isContentWriterGateType(t: string): t is ContentWriterGateType {
    return VALID_GATE_TYPES.has(t);
}

/**
 * Strips characters that could be interpreted as HTML or prompt fragments.
 * Conservative: allows letters, numbers, spaces, and common punctuation.
 */
function sanitize(value: string, maxLen: number): string {
    return value
        .replace(/[<>"'`\\]/g, '')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, maxLen);
}

/**
 * Build a fully-validated, display-safe HumanGateRecord from user-supplied input.
 *
 * SECURITY: title and topic are sanitized. All label/question text comes from
 * fixed template strings — never from user-supplied draft content.
 */
export function buildHumanGateRecord(input: HumanGateInput): HumanGateRecord {
    const { gateType } = input;
    return {
        gateType,
        label: GATE_LABELS[gateType],
        question: GATE_QUESTIONS[gateType],
        category: GATE_CATEGORIES[gateType],
        riskLevel: GATE_RISK_LEVELS[gateType],
        safeTitle: sanitize(input.title, 80),
        safeTopic: sanitize(input.topic, 80),
        wordCount: typeof input.wordCount === 'number' ? input.wordCount : null,
        publishTarget: input.publishTarget ? sanitize(input.publishTarget, 60) : null,
    };
}

/**
 * Build the human-readable approval summary string shown in the dashboard queue.
 *
 * Format: "[Gate Label] "Safe Title" — Gate question."
 *
 * SECURITY: uses only sanitized fields — no raw user content included.
 */
export function buildHumanGateApprovalSummary(record: HumanGateRecord): string {
    const titlePart = record.safeTitle ? `"${record.safeTitle}"` : `"${record.safeTopic}"`;
    return `[${record.label}] ${titlePart} — ${record.question}`;
}

/**
 * Build the impacted scope string for the approval packet.
 * Used to populate the `impacted_scope` field in the dashboard ApprovalItem.
 */
export function buildHumanGateImpactScope(record: HumanGateRecord): string {
    const parts = [`Content: ${record.safeTitle || record.safeTopic}`];
    if (record.publishTarget) {
        parts.push(`Target: ${record.publishTarget}`);
    }
    if (record.wordCount !== null) {
        parts.push(`Words: ${record.wordCount}`);
    }
    return parts.join(' | ');
}

/**
 * Build the risk reason string for the approval packet.
 */
export function buildHumanGateRiskReason(record: HumanGateRecord): string {
    const category = record.category.charAt(0).toUpperCase() + record.category.slice(1);
    return `${category} gate: ${record.label} — agent capability gap requires human expert review.`;
}

/**
 * Build a complete task payload for the runtime queue.
 *
 * The agent or workflow engine MUST use this when enqueuing a human gate task.
 * The 'summary' and 'target' fields are consumed by runtime-server to build
 * the approval packet that appears in the dashboard approval queue.
 *
 * SECURITY: only sanitized fields are included in display-facing strings.
 */
export function buildHumanGateTaskPayload(input: HumanGateInput): Record<string, unknown> {
    const record = buildHumanGateRecord(input);
    // The 'summary' field feeds into 'Change summary:' in the approval packet.
    // Additional lines 'Gate type:' and 'Gate category:' are parsed by parseApprovalPacket in api-gateway.
    const summary = `${buildHumanGateApprovalSummary(record)}\nGate type: ${record.gateType}\nGate category: ${record.category}`;
    return {
        action_type: 'workspace_cw_request_human_gate',
        gateType: record.gateType,
        title: input.title,
        topic: input.topic,
        ...(input.wordCount !== undefined && { wordCount: input.wordCount }),
        ...(input.publishTarget && { publishTarget: input.publishTarget }),
        // Fields consumed by runtime-server to populate the approval packet:
        summary,
        target: buildHumanGateImpactScope(record),
        rollback_plan: 'Content gate — no rollback needed; reject to prevent publication.',
    };
}
