// ============================================================================
// FSD BROWSER DEBUGGER
// Sprint 16 — Full-Stack Developer Role
//
// Live runtime error capture: generates a headless Playwright script, runs
// it via runCommand, and structures the output into a BrowserDebugReport.
// An LLM pass then suggests concrete fixes for each error.
//
// buildPlaywrightDebugScript  → self-contained CJS script (write to disk + run via Node)
// parseBrowserDebugOutput     → structures raw script JSON → BrowserDebugReport
// buildDebugAnalysisPrompt    → LLM prompt: analyse errors + suggest fixes
// applyDebugSuggestions       → merges LLM suggestions back into BrowserError[]
// summariseBrowserReport      → score (0–100) + one-line summary
// ============================================================================

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type BrowserErrorSeverity = 'error' | 'warning' | 'info';

export type BrowserErrorSource =
    | 'console'         // console.error / console.warn
    | 'network'         // HTTP 4xx/5xx, failed fetch
    | 'js_exception'    // uncaught JavaScript error
    | 'csp'             // Content Security Policy violation
    | 'resource'        // failed to load image / script / stylesheet
    | 'other';

export interface BrowserError {
    id:          string;
    source:      BrowserErrorSource;
    severity:    BrowserErrorSeverity;
    message:     string;
    url?:        string;
    stackTrace?: string;
    suggestion?: string;       // filled by LLM analysis
}

export interface NetworkFailure {
    method:     string;
    url:        string;
    status:     number;
    statusText: string;
}

export interface BrowserDebugReport {
    targetUrl:       string;
    errors:          BrowserError[];
    networkFailures: NetworkFailure[];
    score:           number;       // 0–100 (100 = no issues)
    summary:         string;
}

// ---------------------------------------------------------------------------
// buildPlaywrightDebugScript
// ---------------------------------------------------------------------------

/**
 * Returns a self-contained CommonJS script that:
 *   1. Launches headless Chromium via Playwright
 *   2. Captures console errors/warnings, uncaught JS exceptions, HTTP failures
 *   3. Navigates to the target URL and waits for network idle
 *   4. Writes a JSON result object to stdout
 *
 * The caller writes this string to disk (e.g. __fsd_browser_debug.cjs)
 * and executes it via runCommand(['node', path]).
 * Pure function — no side-effects.
 */
export function buildPlaywrightDebugScript(url: string, timeoutMs = 30_000): string {
    return `
// Auto-generated by fsd-browser-debugger — safe to delete after run
'use strict';
const { chromium } = require('playwright');

const TARGET_URL = ${JSON.stringify(url)};
const TIMEOUT_MS = ${timeoutMs};

(async () => {
    let browser;
    const consoleErrors   = [];
    const networkFailures = [];
    const jsExceptions    = [];

    try {
        browser = await chromium.launch({ headless: true });
        const context = await browser.newContext({ ignoreHTTPSErrors: true });
        const page    = await context.newPage();

        // ── Console messages ────────────────────────────────────────────────
        page.on('console', (msg) => {
            const type = msg.type();
            if (type === 'error' || type === 'warning') {
                const loc = msg.location();
                consoleErrors.push({
                    type,
                    text:     msg.text(),
                    location: { url: loc.url, lineNumber: loc.lineNumber },
                });
            }
        });

        // ── Uncaught JS exceptions ──────────────────────────────────────────
        page.on('pageerror', (err) => {
            jsExceptions.push({
                message: err.message,
                stack:   err.stack || '',
            });
        });

        // ── Network failures (4xx / 5xx / connection refused) ───────────────
        page.on('requestfailed', (req) => {
            networkFailures.push({
                method:     req.method(),
                url:        req.url(),
                status:     0,
                statusText: req.failure() ? req.failure().errorText : 'Connection failed',
            });
        });

        page.on('response', (response) => {
            const status = response.status();
            if (status >= 400) {
                networkFailures.push({
                    method:     response.request().method(),
                    url:        response.url(),
                    status,
                    statusText: response.statusText(),
                });
            }
        });

        // ── Navigate ─────────────────────────────────────────────────────────
        try {
            await page.goto(TARGET_URL, { waitUntil: 'networkidle', timeout: TIMEOUT_MS });
        } catch (navErr) {
            consoleErrors.push({
                type:     'error',
                text:     'Navigation error: ' + navErr.message,
                location: {},
            });
        }

    } catch (launchErr) {
        consoleErrors.push({
            type:     'error',
            text:     'Playwright launch error: ' + launchErr.message,
            location: {},
        });
    } finally {
        try { if (browser) await browser.close(); } catch (_) {}
    }

    console.log(JSON.stringify({
        url: TARGET_URL,
        consoleErrors,
        networkFailures,
        jsExceptions,
        capturedAt: new Date().toISOString(),
    }));
})();
`.trim();
}

// ---------------------------------------------------------------------------
// parseBrowserDebugOutput
// ---------------------------------------------------------------------------

interface RawScriptOutput {
    url?:             string;
    consoleErrors?:   Array<{
        type:     string;
        text:     string;
        location?: { url?: string; lineNumber?: number };
    }>;
    networkFailures?: Array<{
        method:     string;
        url:        string;
        status:     number;
        statusText: string;
    }>;
    jsExceptions?:    Array<{
        message: string;
        stack?:  string;
    }>;
}

/**
 * Parses the JSON written to stdout by the Playwright debug script into
 * a structured BrowserDebugReport. Pure function.
 */
export function parseBrowserDebugOutput(jsonOutput: string, targetUrl: string): BrowserDebugReport {
    let raw: RawScriptOutput = {};
    try {
        const start = jsonOutput.indexOf('{');
        const end   = jsonOutput.lastIndexOf('}');
        if (start !== -1 && end !== -1) {
            raw = JSON.parse(jsonOutput.slice(start, end + 1)) as RawScriptOutput;
        }
    } catch {
        // fall through — raw stays empty
    }

    const errors: BrowserError[] = [];
    let idCounter = 1;

    // Console errors / warnings
    for (const ce of raw.consoleErrors ?? []) {
        errors.push({
            id:       `BROWSER-${String(idCounter++).padStart(3, '0')}`,
            source:   detectSource(ce.text),
            severity: ce.type === 'warning' ? 'warning' : 'error',
            message:  ce.text,
            url:      ce.location?.url,
        });
    }

    // Uncaught JS exceptions
    for (const ex of raw.jsExceptions ?? []) {
        errors.push({
            id:         `BROWSER-${String(idCounter++).padStart(3, '0')}`,
            source:     'js_exception',
            severity:   'error',
            message:    ex.message,
            stackTrace: ex.stack || undefined,
        });
    }

    const networkFailures: NetworkFailure[] = (raw.networkFailures ?? []).map((nf) => ({
        method:     nf.method,
        url:        nf.url,
        status:     nf.status,
        statusText: nf.statusText,
    }));

    const { score, summary } = summariseBrowserReport(errors, networkFailures);

    return { targetUrl: raw.url ?? targetUrl, errors, networkFailures, score, summary };
}

function detectSource(text: string): BrowserErrorSource {
    if (/refused to (load|execute|connect|apply|frame)/i.test(text))    return 'csp';
    if (/failed to load|net::err/i.test(text))                          return 'resource';
    if (/fetch|xhr|cors/i.test(text))                                   return 'network';
    if (/uncaught|typeerror|referenceerror|syntaxerror/i.test(text))    return 'js_exception';
    return 'console';
}

// ---------------------------------------------------------------------------
// buildDebugAnalysisPrompt
// ---------------------------------------------------------------------------

/**
 * Crafts an LLM prompt that analyses the captured browser errors and asks for
 * a concrete fix for each one. Pure function.
 */
export function buildDebugAnalysisPrompt(report: BrowserDebugReport, sourceCode?: string): string {
    const errorLines = report.errors.map((e, i) =>
        `${i + 1}. [${e.source}/${e.severity}] ${e.message}`
        + (e.stackTrace ? `\n   Stack: ${e.stackTrace.slice(0, 300)}` : ''),
    ).join('\n');

    const netLines = report.networkFailures.map(
        (nf) => `- ${nf.method} ${nf.url} → ${nf.status} ${nf.statusText}`,
    ).join('\n');

    const codeBlock = sourceCode
        ? `\nRelevant source code:\n\`\`\`\n${sourceCode.slice(0, 3000)}\n\`\`\``
        : '';

    return [
        `You are a senior full-stack developer debugging a live web application.`,
        `The app at "${report.targetUrl}" produced the following runtime errors:`,
        ``,
        errorLines || '(no console errors)',
        netLines ? `\nFailed network requests:\n${netLines}` : '',
        codeBlock,
        ``,
        `For each numbered error, provide a concrete fix.`,
        ``,
        `Return a JSON array where each object has:`,
        `  id    — the error number (1, 2, 3, …) matching the list above`,
        `  cause — root cause in one sentence`,
        `  fix   — specific code change, config change, or dependency fix`,
        ``,
        `No markdown fences, no prose — only the JSON array.`,
    ].filter(Boolean).join('\n');
}

// ---------------------------------------------------------------------------
// applyDebugSuggestions
// ---------------------------------------------------------------------------

/**
 * Merges LLM fix suggestions back into the BrowserError array by index.
 * Pure function.
 */
export function applyDebugSuggestions(raw: string, errors: BrowserError[]): BrowserError[] {
    const cleaned = raw.replace(/^```[a-z]*\n?/im, '').replace(/```\s*$/im, '').trim();
    const start   = cleaned.indexOf('[');
    const end     = cleaned.lastIndexOf(']');
    if (start === -1 || end === -1) return errors;

    try {
        const suggestions = JSON.parse(cleaned.slice(start, end + 1)) as Array<{
            id?:    number;
            cause?: string;
            fix?:   string;
        }>;

        return errors.map((err, idx) => {
            const s = suggestions.find((item) => item.id === idx + 1);
            if (!s) return err;
            const parts = [s.cause, s.fix ? `Fix: ${s.fix}` : ''].filter(Boolean);
            return { ...err, suggestion: parts.join(' — ') || err.suggestion };
        });
    } catch {
        return errors;
    }
}

// ---------------------------------------------------------------------------
// summariseBrowserReport
// ---------------------------------------------------------------------------

/**
 * Computes a 0–100 quality score and a one-line summary. Pure function.
 */
export function summariseBrowserReport(
    errors:          BrowserError[],
    networkFailures: NetworkFailure[],
): { score: number; summary: string } {
    const errorCount   = errors.filter((e) => e.severity === 'error').length;
    const warningCount = errors.filter((e) => e.severity === 'warning').length;
    const serverErrors = networkFailures.filter((nf) => nf.status >= 500).length;

    const score = Math.max(0, 100 - errorCount * 15 - warningCount * 5 - serverErrors * 10);

    if (errors.length === 0 && networkFailures.length === 0) {
        return { score: 100, summary: 'No runtime errors detected.' };
    }

    const worst = errors.find((e) => e.severity === 'error') ?? errors[0]!;
    return {
        score,
        summary: `Runtime debug: score ${score}/100 — ${errorCount} error(s), ${warningCount} warning(s), ${networkFailures.length} network failure(s). Worst: ${worst.message.slice(0, 80)}`,
    };
}
