// ============================================================================
// FSD PERF PROFILER
// Sprint 16 — Full-Stack Developer Role
//
// Live CPU hot-path detection via Chrome DevTools Protocol (CDP).
// Playwright attaches a CDP session, enables the V8 Profiler domain, records
// samples for N milliseconds, then returns a ranked list of hot functions —
// exactly what a developer sees in the Chrome DevTools Performance tab.
//
// buildPlaywrightProfilingScript → self-contained CJS script (write + run via Node)
// parseCpuProfile               → structures V8 .cpuprofile JSON → CpuProfileReport
// buildPerfOptimizationPrompt   → LLM prompt: analyse hot functions + suggest fixes
// applyPerfSuggestions          → merges LLM hints back into HotFunction[]
// summarisePerfProfile          → score (0–100) + one-line summary
// ============================================================================

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface HotFunction {
    rank:         number;
    functionName: string;    // "(anonymous)" if unnamed
    url:          string;    // source file URL
    lineNumber:   number;
    hitCount:     number;    // raw V8 sample count
    selfPercent:  number;    // % of total samples on this frame (1 d.p.)
    suggestion?:  string;    // filled by LLM pass
}

export interface CpuProfileReport {
    targetUrl:    string;
    totalSamples: number;
    durationMs:   number;
    hotFunctions: HotFunction[];   // top ≤15 by selfPercent, idle excluded
    score:        number;          // 0–100 (100 = well-distributed, no hotspot)
    summary:      string;
}

// ---------------------------------------------------------------------------
// buildPlaywrightProfilingScript
// ---------------------------------------------------------------------------

/**
 * Returns a self-contained CommonJS script that:
 *   1. Launches headless Chromium via Playwright
 *   2. Opens a CDP session and enables the V8 Profiler domain
 *   3. Navigates to the target URL and waits for the page to load
 *   4. Records CPU samples for `durationMs` milliseconds
 *   5. Writes the raw V8 profile JSON to stdout
 *
 * The caller writes this string to disk (__fsd_perf_profile.cjs)
 * and runs it via runCommand(['node', path]).
 * Pure function — no side-effects.
 */
export function buildPlaywrightProfilingScript(url: string, durationMs = 5_000): string {
    return `
// Auto-generated by fsd-perf-profiler — safe to delete after run
'use strict';
const { chromium } = require('playwright');

const TARGET_URL  = ${JSON.stringify(url)};
const DURATION_MS = ${durationMs};

(async () => {
    let browser;
    try {
        browser = await chromium.launch({ headless: true });
        const context = await browser.newContext({ ignoreHTTPSErrors: true });
        const page    = await context.newPage();

        // ── Navigate first so the page's JS is loaded ───────────────────────
        try {
            await page.goto(TARGET_URL, { waitUntil: 'load', timeout: 30000 });
        } catch (navErr) {
            console.log(JSON.stringify({
                url: TARGET_URL, durationMs: DURATION_MS,
                error: 'Navigation failed: ' + navErr.message, profile: null,
            }));
            return;
        }

        // ── Attach CDP session ───────────────────────────────────────────────
        const client = await context.newCDPSession(page);
        await client.send('Profiler.enable');
        // 100 μs sampling interval (default is 1000 μs — finer granularity)
        await client.send('Profiler.setSamplingInterval', { interval: 100 });

        // ── Profile for the requested duration ───────────────────────────────
        await client.send('Profiler.start');
        await new Promise((resolve) => setTimeout(resolve, DURATION_MS));
        const { profile } = await client.send('Profiler.stop');

        await client.detach();

        console.log(JSON.stringify({
            url:        TARGET_URL,
            durationMs: DURATION_MS,
            profile,
            capturedAt: new Date().toISOString(),
        }));

    } catch (err) {
        console.log(JSON.stringify({
            url:        TARGET_URL,
            durationMs: DURATION_MS,
            error:      err.message,
            profile:    null,
        }));
    } finally {
        try { if (browser) await browser.close(); } catch (_) {}
    }
})();
`.trim();
}

// ---------------------------------------------------------------------------
// parseCpuProfile
// ---------------------------------------------------------------------------

interface V8ProfileNode {
    id:        number;
    callFrame: {
        functionName: string;
        scriptId:     string;
        url:          string;
        lineNumber:   number;
        columnNumber: number;
    };
    hitCount:  number;
    children?: number[];
}

interface V8Profile {
    nodes:       V8ProfileNode[];
    startTime:   number;
    endTime:     number;
    samples?:    number[];
    timeDeltas?: number[];
}

interface RawProfileOutput {
    url:        string;
    durationMs: number;
    profile:    V8Profile | null;
    error?:     string;
    capturedAt?: string;
}

// Functions whose names indicate browser/engine idle time — excluded from hot list
const IDLE_FRAMES = new Set(['(idle)', '(program)', '(garbage collector)', 'v8::internal']);

/**
 * Parses the JSON written to stdout by the profiling script into a
 * structured CpuProfileReport ranked by self-time. Pure function.
 */
export function parseCpuProfile(rawOutput: string, fallbackUrl = ''): CpuProfileReport {
    let data: RawProfileOutput = { url: fallbackUrl, durationMs: 0, profile: null };

    try {
        const start = rawOutput.indexOf('{');
        const end   = rawOutput.lastIndexOf('}');
        if (start !== -1 && end !== -1) {
            data = JSON.parse(rawOutput.slice(start, end + 1)) as RawProfileOutput;
        }
    } catch {
        // fall through — use empty data
    }

    const emptyReport = (msg: string): CpuProfileReport => ({
        targetUrl:    data.url || fallbackUrl,
        totalSamples: 0,
        durationMs:   data.durationMs,
        hotFunctions: [],
        score:        100,
        summary:      msg,
    });

    if (!data.profile) {
        const msg = data.error
            ? `Profiling error: ${data.error}`
            : 'No profile data — ensure Playwright is installed (npm install playwright).';
        return emptyReport(msg);
    }

    const nodes        = data.profile.nodes ?? [];
    const sampleCount  = (data.profile.samples ?? []).length;
    // Fall back to sum of hitCounts when samples array is absent
    const totalSamples = sampleCount > 0
        ? sampleCount
        : nodes.reduce((s, n) => s + (n.hitCount ?? 0), 0);

    if (totalSamples === 0) return emptyReport('Profile captured 0 samples — page may be idle.');

    // Rank non-idle nodes by hitCount descending
    const ranked = nodes
        .filter((n) => (n.hitCount ?? 0) > 0 && !isIdleFrame(n.callFrame.functionName))
        .sort((a, b) => (b.hitCount ?? 0) - (a.hitCount ?? 0))
        .slice(0, 15);

    const hotFunctions: HotFunction[] = ranked.map((node, i) => ({
        rank:         i + 1,
        functionName: node.callFrame.functionName || '(anonymous)',
        url:          node.callFrame.url,
        lineNumber:   node.callFrame.lineNumber,
        hitCount:     node.hitCount ?? 0,
        selfPercent:  parseFloat(((node.hitCount / totalSamples) * 100).toFixed(1)),
    }));

    const { score, summary } = summarisePerfProfile(hotFunctions, totalSamples, data.url);
    return { targetUrl: data.url, totalSamples, durationMs: data.durationMs, hotFunctions, score, summary };
}

function isIdleFrame(name: string): boolean {
    if (!name) return false;
    for (const idle of IDLE_FRAMES) {
        if (name.startsWith(idle)) return true;
    }
    return false;
}

// ---------------------------------------------------------------------------
// buildPerfOptimizationPrompt
// ---------------------------------------------------------------------------

/**
 * Crafts the LLM prompt that analyses the hot functions and asks for
 * specific optimisation suggestions for the worst offenders. Pure function.
 */
export function buildPerfOptimizationPrompt(
    report:     CpuProfileReport,
    sourceCode?: string,
): string {
    const hotList = report.hotFunctions.slice(0, 10).map((fn) =>
        `${fn.rank}. ${fn.functionName} — ${fn.selfPercent}% of CPU (${fn.hitCount} samples)`
        + (fn.url ? `\n   Source: ${fn.url}${fn.lineNumber ? `:${fn.lineNumber}` : ''}` : ''),
    ).join('\n');

    const codeBlock = sourceCode
        ? `\nRelevant source code:\n\`\`\`\n${sourceCode.slice(0, 3000)}\n\`\`\``
        : '';

    return [
        `You are a senior performance engineer analysing a V8 CPU profile.`,
        `App URL: ${report.targetUrl}`,
        `Profile duration: ${report.durationMs}ms, ${report.totalSamples} total samples.`,
        ``,
        `Top CPU hot functions (by self-time %):`,
        hotList,
        codeBlock,
        ``,
        `For each numbered function, provide a concrete optimisation.`,
        `Focus on: memoisation, algorithm complexity, unnecessary re-renders,`,
        `expensive DOM operations, synchronous blocking, or missing lazy-loading.`,
        ``,
        `Return a JSON array where each object has:`,
        `  id          — matches the function number (1, 2, 3, …)`,
        `  cause       — why this function is a hotspot (one sentence)`,
        `  suggestion  — specific code change or architectural fix`,
        `  impact      — expected improvement: high | medium | low`,
        ``,
        `No markdown fences, no prose — only the JSON array.`,
    ].filter(Boolean).join('\n');
}

// ---------------------------------------------------------------------------
// applyPerfSuggestions
// ---------------------------------------------------------------------------

/**
 * Merges LLM optimisation suggestions back into the HotFunction array.
 * Pure function.
 */
export function applyPerfSuggestions(raw: string, hotFunctions: HotFunction[]): HotFunction[] {
    const cleaned = raw.replace(/^```[a-z]*\n?/im, '').replace(/```\s*$/im, '').trim();
    const start   = cleaned.indexOf('[');
    const end     = cleaned.lastIndexOf(']');
    if (start === -1 || end === -1) return hotFunctions;

    try {
        const suggestions = JSON.parse(cleaned.slice(start, end + 1)) as Array<{
            id?:         number;
            cause?:      string;
            suggestion?: string;
            impact?:     string;
        }>;

        return hotFunctions.map((fn) => {
            const s = suggestions.find((item) => item.id === fn.rank);
            if (!s) return fn;
            const parts = [
                s.cause,
                s.suggestion ? `Fix: ${s.suggestion}` : '',
                s.impact     ? `(${s.impact} impact)`  : '',
            ].filter(Boolean);
            return { ...fn, suggestion: parts.join(' — ') };
        });
    } catch {
        return hotFunctions;
    }
}

// ---------------------------------------------------------------------------
// summarisePerfProfile
// ---------------------------------------------------------------------------

/**
 * Computes a 0–100 score and one-line summary from the hot function list.
 *
 * Scoring model:
 *   - Ideal: no single function over 5% self-time → score ~100
 *   - Each percent of the top function costs ~1.5 score points
 *   - Second function contributes half as much
 * Pure function.
 */
export function summarisePerfProfile(
    hotFunctions: HotFunction[],
    totalSamples: number,
    targetUrl:    string,
): { score: number; summary: string } {
    if (hotFunctions.length === 0 || totalSamples === 0) {
        return { score: 100, summary: 'No hot functions detected — app appears idle or is well-optimised.' };
    }

    const top    = hotFunctions[0]!;
    const second = hotFunctions[1];

    const score = Math.max(
        0,
        Math.round(100 - top.selfPercent * 1.5 - (second?.selfPercent ?? 0) * 0.5),
    );

    const topLabel = top.functionName === '(anonymous)'
        ? `anonymous fn at ${top.url ? top.url.split('/').pop() ?? top.url : 'unknown'}:${top.lineNumber}`
        : top.functionName;

    return {
        score,
        summary: `CPU profile (${totalSamples} samples): score ${score}/100. Hot path: "${topLabel}" at ${top.selfPercent}% self-time. ${hotFunctions.length} functions profiled.`,
    };
}
