/**
 * GDPR-compliant email disclosure footer.
 *
 * Appended to every external-facing email sent by an AgentFarm agent. Satisfies:
 *  - EU AI Act Art. 52 — disclosure that content was generated by an AI system
 *  - GDPR Recital 47  — right to object / opt out of automated processing
 *  - FTC AI guidelines — clear, conspicuous disclosure of AI involvement
 *
 * Usage:
 *   body = appendGdprFooter(body, { optOutUrl: 'https://...', agentDisplayName: 'Alex' });
 */

export interface GdprFooterOptions {
    /** Full URL of the opt-out / preference-centre page. */
    optOutUrl: string;
    /** Optional display name of the agent (e.g. "Alex"). */
    agentDisplayName?: string;
}

const SEPARATOR = '\n\n---\n';

export function buildGdprEmailFooter(options: GdprFooterOptions): string {
    const { optOutUrl, agentDisplayName } = options;
    const agentClause = agentDisplayName
        ? `This message was sent by ${agentDisplayName}, an AI agent`
        : 'This message was sent by an AI agent';
    return [
        SEPARATOR,
        `${agentClause} operating on behalf of AgentFarm.`,
        `To opt out of communications from this agent, visit: ${optOutUrl}`,
    ].join('\n');
}

export function appendGdprFooter(body: string, options: GdprFooterOptions): string {
    return body + buildGdprEmailFooter(options);
}

/** Resolves the opt-out URL from the environment, with a safe fallback. */
export function resolveOptOutUrl(tenantId?: string): string {
    const base = process.env['AGENT_OPT_OUT_BASE_URL'] ?? 'https://agentfarm.dev/optout';
    return tenantId ? `${base}?tenant=${encodeURIComponent(tenantId)}` : base;
}
